# k-Nearest Neighbor

In [2]:
import numpy as np
import pandas as pd
import scipy

import matplotlib.pyplot as plt
from pylab import rcParams

import urllib

import sklearn
from sklearn import neighbors
from sklearn.neighbors import KNeighborsClassifier

from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("pima-indians-diabetes.csv")

In [5]:
df.head(15)

,Number_pregnant,Glucose_concentration,Blood_pressure,Triceps,Insulin,BMI,Pedigree,Age,Class,Group
0,6,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,50,1,B
1,1,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,31,0,C
2,8,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,32,1,B
3,1,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,21,0,B
4,0,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,33,1,C
5,5,0.582915,0.606557,0.000000,0.000000,0.381520,0.052519,30,0,A
6,3,0.391960,0.409836,0.323232,0.104019,0.461997,0.072588,26,1,C
7,10,0.577889,0.000000,0.000000,0.000000,0.526080,0.023911,29,0,A
8,2,0.989950,0.573770,0.454545,0.641844,0.454545,0.034159,53,1,D
9,8,0.628141,0.786885,0.000000,0.000000,0.000000,0.065756,54,1,A
10,4,0.552764,0.754098,0.000000,0.000000,0.560358,0.048249,30,0,D
11,10,0.844221,0.606557,0.000000,0.000000,0.566319,0.195986,34,1,C
12,10,0.698492,0.655738,0.000000,0.000000,0.403875,0.581981,57,0,C
13,1,0.949749,0.491803,0.232323,1.000000,0.448584,0.136635,59,1,A
14,5,0.834171,0.590164,0.191919,0.206856,0.384501,0.217336,51,1,B

# Link for knowing fill na/NAN values in dataframe: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html

In [6]:
df.fillna(method='ffill')

,Number_pregnant,Glucose_concentration,Blood_pressure,Triceps,Insulin,BMI,Pedigree,Age,Class,Group
0,6,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,50,1,B
1,1,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,31,0,C
2,8,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,32,1,B
3,1,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,21,0,B
4,0,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,33,1,C
5,5,0.582915,0.606557,0.000000,0.000000,0.381520,0.052519,30,0,A
6,3,0.391960,0.409836,0.323232,0.104019,0.461997,0.072588,26,1,C
7,10,0.577889,0.000000,0.000000,0.000000,0.526080,0.023911,29,0,A
8,2,0.989950,0.573770,0.454545,0.641844,0.454545,0.034159,53,1,D
9,8,0.628141,0.786885,0.000000,0.000000,0.000000,0.065756,54,1,A
10,4,0.552764,0.754098,0.000000,0.000000,0.560358,0.048249,30,0,D
11,10,0.844221,0.606557,0.000000,0.000000,0.566319,0.195986,34,1,C
12,10,0.698492,0.655738,0.000000,0.000000,0.403875,0.581981,57,0,C
13,1,0.949749,0.491803,0.232323,1.000000,0.448584,0.136635,59,1,A
14,5,0.834171,0.590164,0.191919,0.206856,0.384501,0.217336,51,1,B
15,7,0.502513,0.000000,0.000000,0.000000,0.447094,0.173356,32,1,A
16,0,0.592965,0.688525,0.474747,0.271868,0.682563,0.201964,31,1,B
17,7,0.537688,0.606557,0.000000,0.000000,0.441133,0.075149,31,1,B
18,1,0.517588,0.245902,0.383838,0.098109,0.645306,0.044833,33,0,A
19,1,0.577889,0.573770,0.303030,0.113475,0.515648,0.192570,32,1,A
20,3,0.633166,0.721311,0.414141,0.277778,0.585693,0.267293,27,0,C
21,8,0.497487,0.688525,0.000000,0.000000,0.527571,0.132365,50,0,C
22,7,0.984925,0.737705,0.000000,0.000000,0.593145,0.159266,41,1,B
23,9,0.597990,0.655738,0.353535,0.000000,0.432191,0.078992,29,1,C
24,11,0.718593,0.770492,0.333333,0.172577,0.545455,0.075149,51,1,D
25,10,0.628141,0.573770,0.262626,0.135934,0.463487,0.054227,41,1,D
26,7,0.738693,0.622951,0.000000,0.000000,0.587183,0.076430,43,1,D
27,1,0.487437,0.540984,0.151515,0.165485,0.345753,0.174637,22,0,A
28,13,0.728643,0.672131,0.191919,0.130024,0.330849,0.071307,57,0,C
29,5,0.587940,0.754098,0.000000,0.000000,0.508197,0.110589,38,0,A
...,...,...,...,...,...,...,...,...,...,...
738,2,0.497487,0.491803,0.171717,0.189125,0.545455,0.160120,21,0,D
739,1,0.512563,0.606557,0.000000,0.000000,0.588674,0.091802,42,1,B
740,11,0.603015,0.655738,0.373737,0.177305,0.630402,0.301879,48,1,C
741,3,0.512563,0.360656,0.202020,0.111111,0.459016,0.137489,26,0,B
742,1,0.547739,0.475410,0.181818,0.137116,0.424739,0.060205,22,0,B
743,9,0.703518,0.770492,0.000000,0.000000,0.487332,0.280102,45,1,D
744,13,0.768844,0.721311,0.373737,0.165485,0.605067,0.467976,39,0,D
745,12,0.502513,0.688525,0.333333,0.124113,0.447094,0.175064,46,0,C
746,1,0.738693,0.770492,0.414141,0.000000,0.734724,0.119556,27,1,D
747,1,0.407035,0.606557,0.414141,0.067376,0.690015,0.434671,32,0,B
748,3,0.939698,0.573770,0.222222,0.236407,0.542474,0.140905,36,1,B
749,6,0.814070,0.508197,0.000000,0.000000,0.362146,0.042699,50,1,B
750,4,0.683417,0.573770,0.000000,0.000000,0.464978,0.471392,22,1,A
751,1,0.608040,0.639344,0.393939,0.087470,0.581222,0.078138,28,0,B
752,3,0.542714,0.508197,0.242424,0.000000,0.387481,0.061913,25,0,C
753,0,0.909548,0.721311,0.444444,0.602837,0.645306,0.061486,26,1,B
754,8,0.773869,0.639344,0.323232,0.000000,0.482861,0.155850,45,1,C
755,1,0.643216,0.721311,0.393939,0.130024,0.543964,0.418019,37,1,A
756,7,0.688442,0.737705,0.414141,0.000000,0.476900,0.133646,39,0,D
757,0,0.618090,0.590164,0.000000,0.000000,0.540984,0.076857,52,1,B
758,1,0.532663,0.622951,0.000000,0.000000,0.558867,0.050811,26,0,C
759,6,0.954774,0.754098,0.000000,0.000000,0.529061,0.085397,66,1,A
760,2,0.442211,0.475410,0.262626,0.018913,0.423249,0.293766,22,0,A
761,9,0.854271,0.606557,0.313131,0.000000,0.655738,0.138770,43,1,B
762,9,0.447236,0.508197,0.000000,0.000000,0.335320,0.027327,33,0,B
763,10,0.507538,0.622951,0.484848,0.212766,0.490313,0.039710,63,0,B
764,2,0.613065,0.573770,0.272727,0.000000,0.548435,0.111870,27,0,A
765,5,0.608040,0.590164,0.232323,0.132388,0.390462,0.071307,30,0,C
766,1,0.633166,0.491803,0.000000,0.000000,0.448584,0.115713,47,1,C
767,1,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,23,0,A

In [7]:
df.fillna(df.mean())

,Number_pregnant,Glucose_concentration,Blood_pressure,Triceps,Insulin,BMI,Pedigree,Age,Class,Group
0,6,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,50,1,B
1,1,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,31,0,C
2,8,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,32,1,B
3,1,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,21,0,B
4,0,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,33,1,C
5,5,0.582915,0.606557,0.000000,0.000000,0.381520,0.052519,30,0,A
6,3,0.391960,0.409836,0.323232,0.104019,0.461997,0.072588,26,1,C
7,10,0.577889,0.000000,0.000000,0.000000,0.526080,0.023911,29,0,A
8,2,0.989950,0.573770,0.454545,0.641844,0.454545,0.034159,53,1,D
9,8,0.628141,0.786885,0.000000,0.000000,0.000000,0.065756,54,1,A
10,4,0.552764,0.754098,0.000000,0.000000,0.560358,0.048249,30,0,D
11,10,0.844221,0.606557,0.000000,0.000000,0.566319,0.195986,34,1,C
12,10,0.698492,0.655738,0.000000,0.000000,0.403875,0.581981,57,0,C
13,1,0.949749,0.491803,0.232323,1.000000,0.448584,0.136635,59,1,A
14,5,0.834171,0.590164,0.191919,0.206856,0.384501,0.217336,51,1,B
15,7,0.502513,0.000000,0.000000,0.000000,0.447094,0.173356,32,1,A
16,0,0.592965,0.688525,0.474747,0.271868,0.682563,0.201964,31,1,B
17,7,0.537688,0.606557,0.000000,0.000000,0.441133,0.075149,31,1,B
18,1,0.517588,0.245902,0.383838,0.098109,0.645306,0.044833,33,0,A
19,1,0.577889,0.573770,0.303030,0.113475,0.515648,0.192570,32,1,A
20,3,0.633166,0.721311,0.414141,0.277778,0.585693,0.267293,27,0,C
21,8,0.497487,0.688525,0.000000,0.000000,0.527571,0.132365,50,0,C
22,7,0.984925,0.737705,0.000000,0.000000,0.593145,0.159266,41,1,B
23,9,0.597990,0.655738,0.353535,0.000000,0.432191,0.078992,29,1,C
24,11,0.718593,0.770492,0.333333,0.172577,0.545455,0.075149,51,1,D
25,10,0.628141,0.573770,0.262626,0.135934,0.463487,0.054227,41,1,D
26,7,0.738693,0.622951,0.000000,0.000000,0.587183,0.076430,43,1,D
27,1,0.487437,0.540984,0.151515,0.165485,0.345753,0.174637,22,0,A
28,13,0.728643,0.672131,0.191919,0.130024,0.330849,0.071307,57,0,C
29,5,0.587940,0.754098,0.000000,0.000000,0.508197,0.110589,38,0,A
...,...,...,...,...,...,...,...,...,...,...
738,2,0.497487,0.491803,0.171717,0.189125,0.545455,0.160120,21,0,D
739,1,0.512563,0.606557,0.000000,0.000000,0.588674,0.091802,42,1,B
740,11,0.603015,0.655738,0.373737,0.177305,0.630402,0.301879,48,1,C
741,3,0.512563,0.360656,0.202020,0.111111,0.459016,0.137489,26,0,B
742,1,0.547739,0.475410,0.181818,0.137116,0.424739,0.060205,22,0,B
743,9,0.703518,0.770492,0.000000,0.000000,0.487332,0.280102,45,1,D
744,13,0.768844,0.721311,0.373737,0.165485,0.605067,0.467976,39,0,D
745,12,0.502513,0.688525,0.333333,0.124113,0.447094,0.175064,46,0,C
746,1,0.738693,0.770492,0.414141,0.000000,0.734724,0.119556,27,1,D
747,1,0.407035,0.606557,0.414141,0.067376,0.690015,0.434671,32,0,B
748,3,0.939698,0.573770,0.222222,0.236407,0.542474,0.140905,36,1,B
749,6,0.814070,0.508197,0.000000,0.000000,0.362146,0.042699,50,1,B
750,4,0.683417,0.573770,0.000000,0.000000,0.464978,0.471392,22,1,A
751,1,0.608040,0.639344,0.393939,0.087470,0.581222,0.078138,28,0,B
752,3,0.542714,0.508197,0.242424,0.000000,0.387481,0.061913,25,0,C
753,0,0.909548,0.721311,0.444444,0.602837,0.645306,0.061486,26,1,B
754,8,0.773869,0.639344,0.323232,0.000000,0.482861,0.155850,45,1,C
755,1,0.643216,0.721311,0.393939,0.130024,0.543964,0.418019,37,1,A
756,7,0.688442,0.737705,0.414141,0.000000,0.476900,0.133646,39,0,D
757,0,0.618090,0.590164,0.000000,0.000000,0.540984,0.076857,52,1,B
758,1,0.532663,0.622951,0.000000,0.000000,0.558867,0.050811,26,0,C
759,6,0.954774,0.754098,0.000000,0.000000,0.529061,0.085397,66,1,A
760,2,0.442211,0.475410,0.262626,0.018913,0.423249,0.293766,22,0,A
761,9,0.854271,0.606557,0.313131,0.000000,0.655738,0.138770,43,1,B
762,9,0.447236,0.508197,0.000000,0.000000,0.335320,0.027327,33,0,B
763,10,0.507538,0.622951,0.484848,0.212766,0.490313,0.039710,63,0,B
764,2,0.613065,0.573770,0.272727,0.000000,0.548435,0.111870,27,0,A
765,5,0.608040,0.590164,0.232323,0.132388,0.390462,0.071307,30,0,C
766,1,0.633166,0.491803,0.000000,0.000000,0.448584,0.115713,47,1,C
767,1,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,23,0,A

In [8]:
df.head(20)

,Number_pregnant,Glucose_concentration,Blood_pressure,Triceps,Insulin,BMI,Pedigree,Age,Class,Group
0,6,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,50,1,B
1,1,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,31,0,C
2,8,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,32,1,B
3,1,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,21,0,B
4,0,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,33,1,C
5,5,0.582915,0.606557,0.000000,0.000000,0.381520,0.052519,30,0,A
6,3,0.391960,0.409836,0.323232,0.104019,0.461997,0.072588,26,1,C
7,10,0.577889,0.000000,0.000000,0.000000,0.526080,0.023911,29,0,A
8,2,0.989950,0.573770,0.454545,0.641844,0.454545,0.034159,53,1,D
9,8,0.628141,0.786885,0.000000,0.000000,0.000000,0.065756,54,1,A
10,4,0.552764,0.754098,0.000000,0.000000,0.560358,0.048249,30,0,D
11,10,0.844221,0.606557,0.000000,0.000000,0.566319,0.195986,34,1,C
12,10,0.698492,0.655738,0.000000,0.000000,0.403875,0.581981,57,0,C
13,1,0.949749,0.491803,0.232323,1.000000,0.448584,0.136635,59,1,A
14,5,0.834171,0.590164,0.191919,0.206856,0.384501,0.217336,51,1,B
15,7,0.502513,0.000000,0.000000,0.000000,0.447094,0.173356,32,1,A
16,0,0.592965,0.688525,0.474747,0.271868,0.682563,0.201964,31,1,B
17,7,0.537688,0.606557,0.000000,0.000000,0.441133,0.075149,31,1,B
18,1,0.517588,0.245902,0.383838,0.098109,0.645306,0.044833,33,0,A
19,1,0.577889,0.573770,0.303030,0.113475,0.515648,0.192570,32,1,A

In [9]:
set(df['Group'])   #to check how many output classes or classifiers

{'A', 'B', 'C', 'D'}

In [10]:
x=df[['Glucose_concentration','Blood_pressure']]

In [11]:
y=df['Group']

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.25, random_state=17)

In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [14]:
classifier = KNeighborsClassifier(n_neighbors =2, metric = 'euclidean')
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [15]:
# Predicting the Test set results
y_pred = classifier.predict(x_test)
y_pred

array(['A', 'C', 'B', 'A', 'A', 'A', 'C', 'A', 'B', 'D', 'C', 'A', 'A',
       'A', 'A', 'B', 'A', 'A', 'B', 'C', 'A', 'D', 'A', 'A', 'A', 'C',
       'B', 'C', 'A', 'C', 'A', 'B', 'B', 'A', 'C', 'A', 'B', 'A', 'C',
       'A', 'B', 'B', 'A', 'A', 'A', 'A', 'C', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'C', 'A', 'B', 'A', 'C', 'C', 'A', 'A', 'A', 'A',
       'D', 'B', 'D', 'A', 'C', 'A', 'D', 'D', 'D', 'A', 'D', 'A', 'A',
       'C', 'B', 'A', 'B', 'B', 'A', 'A', 'D', 'B', 'B', 'A', 'D', 'B',
       'A', 'D', 'A', 'A', 'A', 'B', 'D', 'A', 'C', 'A', 'B', 'D', 'A',
       'A', 'A', 'B', 'B', 'B', 'D', 'C', 'A', 'B', 'C', 'C', 'A', 'C',
       'D', 'A', 'C', 'A', 'A', 'B', 'B', 'A', 'A', 'B', 'A', 'A', 'A',
       'B', 'A', 'A', 'A', 'C', 'A', 'A', 'A', 'B', 'C', 'C', 'B', 'D',
       'B', 'C', 'B', 'A', 'C', 'B', 'A', 'A', 'A', 'A', 'A', 'D', 'D',
       'A', 'C', 'C', 'A', 'A', 'B', 'A', 'A', 'C', 'A', 'B', 'A', 'D',
       'A', 'A', 'A', 'C', 'C', 'D', 'A', 'A', 'B', 'B', 'A', 'C', 'A',
       'B', 'A', 'A', 'A', 'C', 'A', 'D', 'B', 'B', 'C'], dtype=object)

In [16]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[21,  9, 10,  4],
       [35, 11,  9,  5],
       [19, 11, 11,  6],
       [22,  9,  4,  6]], dtype=int64)

In [17]:
metrics.accuracy_score(y_test,y_pred)

0.2552083333333333

In [18]:
for n in range(1,10):
    clf = neighbors.KNeighborsClassifier(n_neighbors=n)
    clf.fit(x_train,y_train)
    print(metrics.accuracy_score(y_test, clf.predict(x_test)))

0.21354166666666666
0.2552083333333333
0.234375
0.1875
0.19791666666666666
0.21354166666666666
0.17708333333333334
0.17708333333333334
0.21354166666666666

## Splitting your data into test and training datasets

In [21]:
#reading dataset from iris -need to classify flowers
dff=pd.read_csv("Iris.csv")
dff.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [27]:
x=dff[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]

In [28]:
x=np.array(x).reshape(-1,1)
x

array([[5.1],
       [3.5],
       [1.4],
       [0.2],
       [4.9],
       [3. ],
       [1.4],
       [0.2],
       [4.7],
       [3.2],
       [1.3],
       [0.2],
       [4.6],
       [3.1],
       [1.5],
       [0.2],
       [5. ],
       [3.6],
       [1.4],
       [0.2],
       [5.4],
       [3.9],
       [1.7],
       [0.4],
       [4.6],
       [3.4],
       [1.4],
       [0.3],
       [5. ],
       [3.4],
       [1.5],
       [0.2],
       [4.4],
       [2.9],
       [1.4],
       [0.2],
       [4.9],
       [3.1],
       [1.5],
       [0.1],
       [5.4],
       [3.7],
       [1.5],
       [0.2],
       [4.8],
       [3.4],
       [1.6],
       [0.2],
       [4.8],
       [3. ],
       [1.4],
       [0.1],
       [4.3],
       [3. ],
       [1.1],
       [0.1],
       [5.8],
       [4. ],
       [1.2],
       [0.2],
       [5.7],
       [4.4],
       [1.5],
       [0.4],
       [5.4],
       [3.9],
       [1.3],
       [0.4],
       [5.1],
       [3.5],
       [1.4],
       [0.3],
       [5.7],
       [3.8],
       [1.7],
       [0.3],
       [5.1],
       [3.8],
       [1.5],
       [0.3],
       [5.4],
       [3.4],
       [1.7],
       [0.2],
       [5.1],
       [3.7],
       [1.5],
       [0.4],
       [4.6],
       [3.6],
       [1. ],
       [0.2],
       [5.1],
       [3.3],
       [1.7],
       [0.5],
       [4.8],
       [3.4],
       [1.9],
       [0.2],
       [5. ],
       [3. ],
       [1.6],
       [0.2],
       [5. ],
       [3.4],
       [1.6],
       [0.4],
       [5.2],
       [3.5],
       [1.5],
       [0.2],
       [5.2],
       [3.4],
       [1.4],
       [0.2],
       [4.7],
       [3.2],
       [1.6],
       [0.2],
       [4.8],
       [3.1],
       [1.6],
       [0.2],
       [5.4],
       [3.4],
       [1.5],
       [0.4],
       [5.2],
       [4.1],
       [1.5],
       [0.1],
       [5.5],
       [4.2],
       [1.4],
       [0.2],
       [4.9],
       [3.1],
       [1.5],
       [0.1],
       [5. ],
       [3.2],
       [1.2],
       [0.2],
       [5.5],
       [3.5],
       [1.3],
       [0.2],
       [4.9],
       [3.1],
       [1.5],
       [0.1],
       [4.4],
       [3. ],
       [1.3],
       [0.2],
       [5.1],
       [3.4],
       [1.5],
       [0.2],
       [5. ],
       [3.5],
       [1.3],
       [0.3],
       [4.5],
       [2.3],
       [1.3],
       [0.3],
       [4.4],
       [3.2],
       [1.3],
       [0.2],
       [5. ],
       [3.5],
       [1.6],
       [0.6],
       [5.1],
       [3.8],
       [1.9],
       [0.4],
       [4.8],
       [3. ],
       [1.4],
       [0.3],
       [5.1],
       [3.8],
       [1.6],
       [0.2],
       [4.6],
       [3.2],
       [1.4],
       [0.2],
       [5.3],
       [3.7],
       [1.5],
       [0.2],
       [5. ],
       [3.3],
       [1.4],
       [0.2],
       [7. ],
       [3.2],
       [4.7],
       [1.4],
       [6.4],
       [3.2],
       [4.5],
       [1.5],
       [6.9],
       [3.1],
       [4.9],
       [1.5],
       [5.5],
       [2.3],
       [4. ],
       [1.3],
       [6.5],
       [2.8],
       [4.6],
       [1.5],
       [5.7],
       [2.8],
       [4.5],
       [1.3],
       [6.3],
       [3.3],
       [4.7],
       [1.6],
       [4.9],
       [2.4],
       [3.3],
       [1. ],
       [6.6],
       [2.9],
       [4.6],
       [1.3],
       [5.2],
       [2.7],
       [3.9],
       [1.4],
       [5. ],
       [2. ],
       [3.5],
       [1. ],
       [5.9],
       [3. ],
       [4.2],
       [1.5],
       [6. ],
       [2.2],
       [4. ],
       [1. ],
       [6.1],
       [2.9],
       [4.7],
       [1.4],
       [5.6],
       [2.9],
       [3.6],
       [1.3],
       [6.7],
       [3.1],
       [4.4],
       [1.4],
       [5.6],
       [3. ],
       [4.5],
       [1.5],
       [5.8],
       [2.7],
       [4.1],
       [1. ],
       [6.2],
       [2.2],
       [4.5],
       [1.5],
       [5.6],
       [2.5],
       [3.9],
       [1.1],
       [5.9],
       [3.2],
       [4.8],
       [1.8],
       [6.1],
       [2.8],
       [4. ],
       [1.3],
       [6.3],
       [2.5],
       [4.9],
       [1.5],
       [6.1],
       [2.8],
       [4.7],
       [1.2],
       [6.4],
       [2.9],
       [4.3],
       [1.3],
       [6.6],
       [3. ],
       [4.4],
       [1.4],
       [6.8],
       [2.8],
       [4.8],
       [1.4],
       [6.7],
       [3. ],
       [5. ],
       [1.7],
       [6. ],
       [2.9],
       [4.5],
       [1.5],
       [5.7],
       [2.6],
       [3.5],
       [1. ],
       [5.5],
       [2.4],
       [3.8],
       [1.1],
       [5.5],
       [2.4],
       [3.7],
       [1. ],
       [5.8],
       [2.7],
       [3.9],
       [1.2],
       [6. ],
       [2.7],
       [5.1],
       [1.6],
       [5.4],
       [3. ],
       [4.5],
       [1.5],
       [6. ],
       [3.4],
       [4.5],
       [1.6],
       [6.7],
       [3.1],
       [4.7],
       [1.5],
       [6.3],
       [2.3],
       [4.4],
       [1.3],
       [5.6],
       [3. ],
       [4.1],
       [1.3],
       [5.5],
       [2.5],
       [4. ],
       [1.3],
       [5.5],
       [2.6],
       [4.4],
       [1.2],
       [6.1],
       [3. ],
       [4.6],
       [1.4],
       [5.8],
       [2.6],
       [4. ],
       [1.2],
       [5. ],
       [2.3],
       [3.3],
       [1. ],
       [5.6],
       [2.7],
       [4.2],
       [1.3],
       [5.7],
       [3. ],
       [4.2],
       [1.2],
       [5.7],
       [2.9],
       [4.2],
       [1.3],
       [6.2],
       [2.9],
       [4.3],
       [1.3],
       [5.1],
       [2.5],
       [3. ],
       [1.1],
       [5.7],
       [2.8],
       [4.1],
       [1.3],
       [6.3],
       [3.3],
       [6. ],
       [2.5],
       [5.8],
       [2.7],
       [5.1],
       [1.9],
       [7.1],
       [3. ],
       [5.9],
       [2.1],
       [6.3],
       [2.9],
       [5.6],
       [1.8],
       [6.5],
       [3. ],
       [5.8],
       [2.2],
       [7.6],
       [3. ],
       [6.6],
       [2.1],
       [4.9],
       [2.5],
       [4.5],
       [1.7],
       [7.3],
       [2.9],
       [6.3],
       [1.8],
       [6.7],
       [2.5],
       [5.8],
       [1.8],
       [7.2],
       [3.6],
       [6.1],
       [2.5],
       [6.5],
       [3.2],
       [5.1],
       [2. ],
       [6.4],
       [2.7],
       [5.3],
       [1.9],
       [6.8],
       [3. ],
       [5.5],
       [2.1],
       [5.7],
       [2.5],
       [5. ],
       [2. ],
       [5.8],
       [2.8],
       [5.1],
       [2.4],
       [6.4],
       [3.2],
       [5.3],
       [2.3],
       [6.5],
       [3. ],
       [5.5],
       [1.8],
       [7.7],
       [3.8],
       [6.7],
       [2.2],
       [7.7],
       [2.6],
       [6.9],
       [2.3],
       [6. ],
       [2.2],
       [5. ],
       [1.5],
       [6.9],
       [3.2],
       [5.7],
       [2.3],
       [5.6],
       [2.8],
       [4.9],
       [2. ],
       [7.7],
       [2.8],
       [6.7],
       [2. ],
       [6.3],
       [2.7],
       [4.9],
       [1.8],
       [6.7],
       [3.3],
       [5.7],
       [2.1],
       [7.2],
       [3.2],
       [6. ],
       [1.8],
       [6.2],
       [2.8],
       [4.8],
       [1.8],
       [6.1],
       [3. ],
       [4.9],
       [1.8],
       [6.4],
       [2.8],
       [5.6],
       [2.1],
       [7.2],
       [3. ],
       [5.8],
       [1.6],
       [7.4],
       [2.8],
       [6.1],
       [1.9],
       [7.9],
       [3.8],
       [6.4],
       [2. ],
       [6.4],
       [2.8],
       [5.6],
       [2.2],
       [6.3],
       [2.8],
       [5.1],
       [1.5],
       [6.1],
       [2.6],
       [5.6],
       [1.4],
       [7.7],
       [3. ],
       [6.1],
       [2.3],
       [6.3],
       [3.4],
       [5.6],
       [2.4],
       [6.4],
       [3.1],
       [5.5],
       [1.8],
       [6. ],
       [3. ],
       [4.8],
       [1.8],
       [6.9],
       [3.1],
       [5.4],
       [2.1],
       [6.7],
       [3.1],
       [5.6],
       [2.4],
       [6.9],
       [3.1],
       [5.1],
       [2.3],
       [5.8],
       [2.7],
       [5.1],
       [1.9],
       [6.8],
       [3.2],
       [5.9],
       [2.3],
       [6.7],
       [3.3],
       [5.7],
       [2.5],
       [6.7],
       [3. ],
       [5.2],
       [2.3],
       [6.3],
       [2.5],
       [5. ],
       [1.9],
       [6.5],
       [3. ],
       [5.2],
       [2. ],
       [6.2],
       [3.4],
       [5.4],
       [2.3],
       [5.9],
       [3. ],
       [5.1],
       [1.8]])

In [31]:
y=dff['Species']

->since we have categorical data in the output column it's better we use onehotencoder instead of label encoder:
https://medium.com/@contactsunny/label-encoder-vs-one-hot-encoder-in-machine-learning-3fc273365621

Above medium articelinfo:
To begin with, you can find the SciKit Learn documentation for Label Encoder here.
Now, let’s consider the following data:

Data from SuperDataScience
In this example, the first column is the country column, which is all text. As you might know by now, we can’t have text in our data if we’re going to run any kind of model on it. So before we can run a model, we need to make this data ready for the model.
And to convert this kind of categorical text data into model-understandable numerical data, we use the Label Encoder class. So all we have to do, to label encode the first column, is import the LabelEncoder class from the sklearn library, fit and transform the first column of the data, and then replace the existing text data with the new encoded data. Let’s have a look at the code.

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
x[:, 0] = labelencoder.fit_transform(x[:, 0])
We’ve assumed that the data is in a variable called ‘x’. After running this piece of code, if you check the value of x, you’ll see that the three countries in the first column have been replaced by the numbers 0, 1, and 2.

That’s all label encoding is about. But depending on the data, label encoding introduces a new problem. For example, we have encoded a set of country names into numerical data. This is actually categorical data and there is no relation, of any kind, between the rows.
The problem here is, since there are different numbers in the same column, the model will misunderstand the data to be in some kind of order, 0 < 1 < 2. But this isn’t the case at all. To overcome this problem, we use One Hot Encoder.

StandardScaler : from sklearn.preprocessing import StandardScaler (understanding)
    It transforms the data in such a manner that it has mean as 0 and standard deviation as 1. ... Standardization is useful for data which has negative values. It arranges the data in normal distribution. 
    It is more useful in classification than regression

In [41]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [42]:
le=LabelEncoder()
oh=OneHotEncoder()

In [44]:
y=le.fit_transform(y)

In [47]:
y=np.array(y).reshape(-1,1)

In [48]:
y=oh.fit_transform(y)

In [49]:
y

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [51]:

from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [53]:
x_rain,x_test,y_train,y_test=train_test_split(x,y,random_state=32,test_size=0.3)

ValueError: Found input variables with inconsistent numbers of samples: [600, 150]

In [50]:
classifier = KNeighborsClassifier(n_neighbors =2, metric = 'euclidean')
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [24]:
df = pd.read_csv("hp_data.csv")

In [25]:
df.head()

,Unnamed: 0,price,place,built,sqft,sale,yearsOld,floor,totalFloor,bhk
0,1341,6300000.0,BTM Layout,Super built-up Area,1450,Resale,5,1,4,1
1,2126,11500000.0,Yelahanka,Super built-up Area,2190,Resale,5,3,5,3
2,816,3800000.0,Whitefield,Super built-up Area,1019,Resale,1,2,5,2
3,2708,10500000.0,Ambalipura,Super built-up Area,1857,Resale,15,4,5,4
4,1041,11500000.0,Yelahanka,Super built-up Area,2190,Resale,5,3,5,3

In [26]:
set(df['bhk'])    #to see what  data is present in df

{1, 2, 3, 4, 6, 15, 17, 18}

In [27]:
len(set(df['bhk']))

8

To begin with, you can find the SciKit Learn documentation for Label Encoder here.
Now, let’s consider the following data:

Data from SuperDataScience
In this example, the first column is the country column, which is all text. As you might know by now, we can’t have text in our data if we’re going to run any kind of model on it. So before we can run a model, we need to make this data ready for the model.
And to convert this kind of categorical text data into model-understandable numerical data, we use the Label Encoder class. So all we have to do, to label encode the first column, is import the LabelEncoder class from the sklearn library, fit and transform the first column of the data, and then replace the existing text data with the new encoded data. Let’s have a look at the code.

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
x[:, 0] = labelencoder.fit_transform(x[:, 0])
We’ve assumed that the data is in a variable called ‘x’. After running this piece of code, if you check the value of x, you’ll see that the three countries in the first column have been replaced by the numbers 0, 1, and 2.

That’s all label encoding is about. But depending on the data, label encoding introduces a new problem. For example, we have encoded a set of country names into numerical data. This is actually categorical data and there is no relation, of any kind, between the rows.
The problem here is, since there are different numbers in the same column, the model will misunderstand the data to be in some kind of order, 0 < 1 < 2. But this isn’t the case at all. To overcome this problem, we use One Hot Encoder.

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['place']=le.fit_transform(df['place'])    #place contains text which is encoded in linear form with numerical data

In [29]:
df.columns

Index(['Unnamed: 0', 'price', 'place', 'built', 'sqft', 'sale', 'yearsOld',
       'floor', 'totalFloor', 'bhk'],
      dtype='object')

In [30]:
x=df[['price','place','sqft','totalFloor']]    #taking four parameters to variable x as input to our model
y=df['bhk']   #passing one variable to output variable

In [ ]:
#practice for

In [31]:
x_train, x_test, Y_train, Y_test = train_test_split(x, y, test_size=.33, random_state=17)   #practice

In [32]:
#feature scaling
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler(feature_range=(0,5))

In [33]:
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsClassifier

In [34]:
cl = neighbors.KNeighborsClassifier(n_neighbors=6,metric='euclidean')
cl.fit(x_train)

TypeError: fit() missing 1 required positional argument: 'y'

In [35]:
x_scaled= mm.fit_transform(x_train)

In [36]:


y_pred = cl.predict(X_test)
metrics.accuracy_score(y_test,y_pred)

NameError: name 'X_test' is not defined

In [25]:

y_pred = cl.predict(X_test)
metrics.accuracy_score(y_test,y_pred)

AttributeError: 'NearestNeighbors' object has no attribute 'predict'

In [ ]:
#above steps are for practice

In [13]:
cars.head()

NameError: name 'cars' is not defined

In [87]:
set(cars.carb)

{1, 2, 3, 4, 6, 8}

In [88]:
X_prime = cars[["mpg","hp","cyl"]]
y= cars[["carb"]]

In [25]:
x=np.array(x)

In [90]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler(feature_range=(0,5))

In [95]:
X_prime.head(3)

    mpg   hp  cyl
0  21.0  110    6
1  21.0  110    6
2  22.8   93    4

In [102]:
np.min(X_prime.cyl)

4

In [98]:
x_scaled[0:3]

array([[2.25531915, 1.02473498, 2.5       ],
       [2.25531915, 1.02473498, 2.5       ],
       [2.63829787, 0.72438163, 0.        ]])

In [91]:
x_scaled = mm.fit_transform(X_prime)

In [104]:
X_train, X_test, y_train, y_test = train_test_split(x_scaled, y, test_size=.33, random_state=17)

types of distances :
1.eucledian distance

from math import*
 
def euclidean_distance(x,y):
 
    return sqrt(sum(pow(a-b,2) for a, b in zip(x, y)))
 
print euclidean_distance([0,3,4,5],[7,6,3,-1])
Script Output:

2.manhattan distance:
from math import*
 
def manhattan_distance(x,y):
 
    return sum(abs(a-b) for a,b in zip(x,y))
 
print manhattan_distance([10,20,10],[10,20,20]).


The Minkowski distance is a generalized metric form of Euclidean distance and Manhattan distance.

In [111]:
from sklearn.neighbors import NearestNeighbors

## Building and training your model with training data

In [28]:
clf = NearestNeighbors(n_neighbors=3,metric='euclidean')

clf.fit(X_train)

NameError: name 'X_train' is not defined

In [34]:
clf = neighbors.KNeighborsClassifier(n_neighbors=6,metric='euclidean')


y_pred = clf.predict(X_test)
metrics.accuracy_score(y_test,y_pred)

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [19]:
y_pred = clf.predict(X_test)
metrics.accuracy_score(y_test,y_pred)

In [20]:
metrics.accuracy_score(y_test,y_pred)

0.2677165354330709

In [39]:
list(zip(y_test,y_pred))

[(3, 3),
 (4, 4),
 (1, 1),
 (1, 1),
 (4, 4),
 (3, 3),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (6, 6),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (18, 18),
 (3, 3),
 (6, 6),
 (6, 6),
 (3, 3),
 (2, 2),
 (1, 1),
 (2, 2),
 (2, 2),
 (1, 1),
 (2, 2),
 (1, 1),
 (1, 1),
 (1, 1),
 (6, 6),
 (3, 3),
 (2, 2),
 (1, 1),
 (2, 2),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (4, 4),
 (1, 1),
 (6, 6),
 (4, 4),
 (1, 1),
 (1, 1),
 (4, 4),
 (1, 1),
 (3, 3),
 (1, 1),
 (18, 18),
 (4, 4),
 (1, 1),
 (2, 2),
 (2, 2),
 (3, 3),
 (3, 3),
 (2, 2),
 (3, 3),
 (1, 1),
 (2, 2),
 (1, 1),
 (1, 1),
 (18, 18),
 (1, 1),
 (3, 3),
 (18, 18),
 (3, 3),
 (1, 1),
 (1, 1),
 (2, 2),
 (3, 3),
 (3, 3),
 (18, 18),
 (2, 2),
 (4, 4),
 (18, 18),
 (3, 3),
 (4, 4),
 (1, 1),
 (6, 6),
 (6, 6),
 (3, 3),
 (1, 1),
 (4, 4),
 (3, 3),
 (3, 3),
 (18, 18),
 (1, 1),
 (2, 2),
 (6, 6),
 (3, 3),
 (1, 1),
 (2, 2),
 (6, 6),
 (2, 2),
 (3, 3),
 (1, 1),
 (2, 2),
 (1, 1),
 (6, 6),
 (1, 1),
 (1, 1),
 (3, 3),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (4, 4),
 (18, 18),
 (4, 4),
 (4, 4),
 (3, 3),
 (3, 3),
 (6, 6),
 (1, 1),
 (18, 18),
 (1, 1),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (6, 6),
 (3, 3),
 (4, 4),
 (1, 1),
 (1, 1),
 (6, 6),
 (4, 4),
 (6, 6),
 (3, 3),
 (4, 4),
 (2, 2),
 (3, 3),
 (3, 3),
 (3, 3),
 (1, 1),
 (6, 6),
 (1, 1),
 (4, 4),
 (6, 6),
 (3, 3),
 (18, 18),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (2, 2),
 (4, 4),
 (1, 1),
 (1, 1),
 (6, 6),
 (18, 18),
 (1, 1),
 (6, 6),
 (2, 2),
 (3, 3),
 (6, 6),
 (1, 1),
 (1, 1),
 (3, 3),
 (1, 1),
 (1, 1),
 (2, 2),
 (1, 1),
 (3, 3),
 (1, 1),
 (6, 6),
 (3, 3),
 (6, 6),
 (1, 1),
 (2, 2),
 (2, 2),
 (3, 3),
 (4, 4),
 (18, 18),
 (1, 1),
 (6, 6),
 (1, 1),
 (3, 3),
 (3, 3),
 (18, 18),
 (1, 1),
 (2, 2),
 (3, 3),
 (1, 1),
 (4, 4),
 (1, 1),
 (1, 1),
 (1, 1),
 (3, 3),
 (6, 6),
 (3, 3),
 (1, 1),
 (3, 3),
 (18, 18),
 (2, 2),
 (6, 6),
 (3, 3),
 (4, 4),
 (6, 6),
 (1, 1),
 (1, 1),
 (3, 3),
 (2, 2),
 (18, 18),
 (3, 3),
 (2, 2),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (3, 3),
 (1, 1),
 (4, 4),
 (2, 2),
 (2, 2),
 (6, 6),
 (6, 6),
 (1, 1),
 (4, 4),
 (1, 1),
 (2, 2),
 (1, 1),
 (3, 3),
 (4, 4),
 (3, 3),
 (6, 6),
 (3, 3),
 (3, 3),
 (2, 2),
 (1, 1),
 (3, 3),
 (1, 1),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (2, 2),
 (3, 3),
 (6, 6),
 (2, 2),
 (18, 18),
 (1, 1),
 (18, 18),
 (1, 1),
 (1, 1),
 (6, 6),
 (4, 4),
 (6, 6),
 (3, 3),
 (3, 3),
 (6, 6),
 (2, 2),
 (6, 6),
 (1, 1),
 (18, 18),
 (2, 2),
 (3, 3),
 (2, 2),
 (4, 4),
 (4, 4),
 (2, 2),
 (3, 3),
 (6, 6),
 (3, 3),
 (1, 1),
 (2, 2),
 (3, 3),
 (6, 6),
 (4, 4),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (3, 3),
 (1, 1),
 (1, 1),
 (2, 2),
 (6, 6),
 (6, 6),
 (2, 2),
 (2, 2),
 (1, 1),
 (3, 3),
 (4, 4),
 (1, 1),
 (2, 2),
 (6, 6),
 (1, 1),
 (3, 3),
 (2, 2),
 (1, 1),
 (3, 3),
 (1, 1),
 (6, 6),
 (1, 1),
 (15, 15),
 (3, 3),
 (18, 18),
 (2, 2),
 (2, 2),
 (3, 3),
 (3, 3),
 (1, 1),
 (18, 18),
 (1, 1),
 (3, 3),
 (18, 18),
 (1, 1),
 (1, 1),
 (3, 3),
 (1, 1),
 (4, 4),
 (1, 1),
 (3, 3),
 (4, 4),
 (3, 3),
 (18, 18),
 (4, 4),
 (18, 18),
 (1, 1),
 (1, 1),
 (1, 1),
 (2, 2),
 (2, 2),
 (2, 2),
 (1, 1),
 (18, 18),
 (18, 18),
 (3, 3),
 (2, 2),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (18, 18),
 (1, 1),
 (3, 3),
 (18, 18),
 (4, 4),
 (2, 2),
 (1, 1),
 (3, 3),
 (3, 3),
 (4, 4),
 (1, 1),
 (1, 1),
 (3, 3),
 (2, 2),
 (2, 2),
 (1, 1),
 (1, 1),
 (6, 6),
 (1, 1),
 (18, 18),
 (1, 1),
 (1, 1),
 (3, 3),
 (3, 3),
 (6, 6),
 (3, 3),
 (4, 4),
 (3, 3),
 (1, 1),
 (3, 3),
 (4, 4),
 (3, 3),
 (4, 4),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (1, 1),
 (2, 2),
 (3, 3),
 (3, 3),
 (3, 3),
 (2, 2),
 (1, 1),
 (3, 3),
 (18, 18),
 (2, 2),
 (1, 1),
 (1, 1),
 (18, 18),
 (6, 6),
 (1, 1),
 (6, 6),
 (3, 3),
 (4, 4),
 (1, 1),
 (2, 2),
 (1, 1),
 (4, 4),
 (1, 1),
 (3, 3),
 (1, 1),
 (1, 1),
 (1, 1),
 (2, 2),
 (3, 3),
 (2, 2),
 (6, 6),
 (1, 1),
 (3, 3),
 (3, 3),
 (3, 3),
 (4, 4),
 (1, 1),
 (1, 1),
 (18, 18),
 (2, 2),
 (3, 3),
 (3, 3),
 (2, 2),
 (3, 3),
 (3, 3),
 (4, 4),
 (6, 6),
 (3, 3),
 (1, 1),
 (3, 3),
 (3, 3),
 (2, 2),
 (2, 2),
 (1, 1),
 (1, 1),
 (3, 3),
 (18, 18),
 (1, 1),
 (6, 6),
 (18, 18),
 (3, 3),
 (3, 3),
 (3, 3),
 (6, 6),
 (18, 18),
 (4, 4),
 (3, 3),
 (6, 6),
 (3, 3),
 (2, 2),
 (2, 2),
 (1, 1),
 (18, 18),
 (1, 1),
 (18, 18),
 (3, 3),
 (1, 1),
 (2, 2),
 (18, 18),
 (2, 2),
 (4, 4),
 (1, 1),
 (4, 4),
 (4, 4),
 (3, 3),
 (3, 3),
 (4, 4),
 (3, 3),
 (1, 1),
 (4, 4),
 (1, 1),
 (2, 2),
 (3, 3),
 (2, 2),
 (3, 3),
 (3, 3),
 (3, 3),
 (4, 4),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (6, 6),
 (1, 1),
 (1, 1),
 (1, 1),
 (3, 3),
 (18, 18),
 (3, 3),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (1, 1),
 (3, 3),
 (1, 1),
 (4, 4),
 (18, 18),
 (4, 4),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (1, 1),
 (2, 2),
 (1, 1),
 (1, 1),
 (1, 1),
 (6, 6),
 (1, 1),
 (3, 3),
 (3, 3),
 (6, 6),
 (18, 18),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (1, 1),
 (6, 6),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (1, 1),
 (2, 2),
 (6, 6),
 (1, 1),
 (6, 6),
 (1, 1),
 (4, 4),
 (2, 2),
 (3, 3),
 (1, 1),
 (4, 4),
 (2, 2),
 (6, 6),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (18, 18),
 (2, 2),
 (1, 1),
 (1, 1),
 (2, 2),
 (6, 6),
 (6, 6),
 (3, 3),
 (6, 6),
 (1, 1),
 (18, 18),
 (1, 1),
 (1, 1),
 (1, 1),
 (4, 4),
 (3, 3),
 (6, 6),
 (1, 1),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (6, 6),
 (3, 3),
 (2, 2),
 (3, 3),
 (3, 3),
 (1, 1),
 (18, 18),
 (1, 1),
 (1, 1),
 (3, 3),
 (6, 6),
 (3, 3),
 (3, 3),
 (2, 2),
 (2, 2),
 (3, 3),
 (1, 1),
 (6, 6),
 (2, 2),
 (6, 6),
 (4, 4),
 (1, 1),
 (1, 1),
 (3, 3),
 (4, 4),
 (6, 6),
 (4, 4),
 (4, 4),
 (1, 1),
 (2, 2),
 (1, 1),
 (1, 1),
 (4, 4),
 (6, 6),
 (18, 18),
 (3, 3),
 (3, 3),
 (3, 3),
 (1, 1),
 (3, 3),
 (18, 18),
 (18, 18),
 (4, 4),
 (1, 1),
 (3, 3),
 (6, 6),
 (3, 3),
 (3, 3),
 (3, 3),
 (3, 3),
 (4, 4),
 (4, 4),
 (3, 3),
 (6, 6),
 (3, 3),
 (6, 6),
 (1, 1),
 (2, 2),
 (3, 3),
 (3, 3),
 (1, 1),
 (3, 3),
 (3, 3),
 (2, 2),
 (18, 18),
 (1, 1),
 (3, 3),
 (18, 18),
 (18, 18),
 (1, 1),
 (3, 3),
 (6, 6),
 (1, 1),
 (6, 6),
 (4, 4),
 (4, 4),
 (2, 2),
 (1, 1),
 (18, 18),
 (3, 3),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (4, 4),
 (3, 3),
 (4, 4),
 (1, 1),
 (6, 6),
 (1, 1),
 (1, 1),
 (4, 4),
 (6, 6),
 (2, 2),
 (1, 1),
 (3, 3),
 (4, 4),
 (18, 18),
 (2, 2),
 (4, 4),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (1, 1),
 (1, 1),
 (3, 3),
 (1, 1),
 (1, 1),
 (4, 4),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (4, 4),
 (18, 18),
 (4, 4),
 (18, 18),
 (1, 1),
 (2, 2),
 (1, 1),
 (3, 3),
 (1, 1),
 (4, 4),
 (3, 3),
 (3, 3),
 (6, 6),
 (18, 18),
 (3, 3),
 (3, 3),
 (1, 1),
 (2, 2),
 (6, 6),
 (1, 1),
 (4, 4),
 (18, 18),
 (1, 1),
 (1, 1),
 (1, 1),
 (3, 3),
 (3, 3),
 (3, 3),
 (4, 4),
 (6, 6),
 (6, 6),
 (4, 4),
 (6, 6),
 (1, 1),
 (6, 6),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (2, 2),
 (1, 1),
 (3, 3),
 (3, 3),
 (6, 6),
 (1, 1),
 (6, 6),
 (1, 1),
 (3, 3),
 (1, 1),
 (2, 2),
 (18, 18),
 (2, 2),
 (3, 3),
 (3, 3),
 (1, 1),
 (6, 6),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (1, 1),
 (2, 2),
 (18, 18),
 (6, 6),
 (3, 3),
 (6, 6),
 (3, 3),
 (6, 6),
 (1, 1),
 (6, 6),
 (4, 4),
 (1, 1),
 (1, 1),
 (3, 3),
 (2, 2),
 (3, 3),
 (2, 2),
 (1, 1),
 (6, 6),
 (6, 6),
 (3, 3),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (4, 4),
 (6, 6),
 (1, 1),
 (3, 3),
 (17, 17),
 (4, 4),
 (1, 1),
 (18, 18),
 (1, 1),
 (3, 3),
 (4, 4),
 (1, 1),
 (1, 1),
 (1, 1),
 (4, 4),
 (1, 1),
 (3, 3),
 (2, 2),
 (1, 1),
 (1, 1),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (2, 2),
 (3, 3),
 (18, 18),
 (2, 2),
 (2, 2),
 (1, 1),
 (3, 3),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (1, 1),
 (18, 18),
 (2, 2),
 (3, 3),
 (6, 6),
 (2, 2),
 (3, 3),
 (3, 3),
 (3, 3),
 (1, 1),
 (6, 6),
 (6, 6),
 (18, 18),
 (4, 4),
 (3, 3),
 (1, 1),
 (4, 4),
 (6, 6),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (6, 6),
 (3, 3),
 (3, 3),
 (1, 1),
 (4, 4),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (6, 6),
 (1, 1),
 (6, 6),
 (3, 3),
 (18, 18),
 (6, 6),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (3, 3),
 (2, 2),
 (1, 1),
 (1, 1),
 (6, 6),
 (2, 2),
 (1, 1),
 (3, 3),
 (3, 3),
 (18, 18),
 (1, 1),
 (1, 1),
 (4, 4),
 (4, 4),
 (1, 1),
 (3, 3),
 (3, 3),
 (2, 2),
 (18, 18),
 (1, 1),
 (6, 6),
 (1, 1),
 (4, 4),
 (1, 1),
 (3, 3),
 (4, 4),
 (3, 3),
 (18, 18),
 (3, 3),
 (1, 1),
 (1, 1),
 (6, 6),
 (4, 4),
 (18, 18),
 (3, 3),
 (1, 1),
 (4, 4),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (4, 4),
 (2, 2),
 (1, 1),
 (18, 18),
 (6, 6),
 (3, 3),
 (3, 3),
 (18, 18),
 (3, 3),
 (1, 1),
 (2, 2),
 (3, 3),
 (3, 3),
 (2, 2),
 (3, 3),
 (4, 4),
 (3, 3),
 (6, 6),
 (3, 3),
 (18, 18),
 (3, 3),
 (1, 1),
 (3, 3),
 (3, 3),
 (1, 1),
 (6, 6),
 (1, 1),
 (2, 2),
 (2, 2),
 (1, 1),
 (18, 18),
 (2, 2),
 (2, 2),
 (3, 3),
 (2, 2),
 (3, 3),
 (2, 2),
 (18, 18),
 (1, 1),
 (1, 1),
 (3, 3),
 (1, 1),
 (18, 18),
 (3, 3),
 (2, 2),
 (3, 3),
 (2, 2),
 (3, 3),
 (1, 1),
 (4, 4),
 (18, 18),
 (1, 1),
 (6, 6),
 (1, 1),
 (3, 3),
 (3, 3),
 (4, 4),
 (1, 1),
 (1, 1),
 (3, 3),
 (1, 1),
 (4, 4),
 (1, 1),
 (3, 3),
 (3, 3),
 (4, 4),
 (18, 18),
 (3, 3),
 (3, 3),
 (1, 1),
 (1, 1),
 (4, 4),
 (6, 6),
 (3, 3),
 (3, 3),
 (18, 18),
 (3, 3),
 (4, 4),
 (18, 18),
 (3, 3),
 (1, 1),
 (4, 4),
 (6, 6),
 (2, 2),
 (6, 6),
 (3, 3),
 (3, 3),
 (6, 6),
 (3, 3),
 (1, 1),
 (1, 1),
 (6, 6),
 (4, 4),
 (2, 2),
 (1, 1),
 (18, 18),
 (2, 2),
 (1, 1),
 (3, 3),
 ...]

In [64]:
from sklearn.metrics import confusion_matrix,classification_report

In [65]:
confusion_matrix(y_test,y_pred)

array([[358,   0,   0,   0,   0,   0,   0,   0],
       [  0, 133,   0,   0,   0,   0,   0,   0],
       [  0,   0, 341,   0,   0,   0,   0,   0],
       [  0,   0,   0, 111,   0,   0,   0,   0],
       [  0,   0,   0,   0, 123,   0,   0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0],
       [  0,   0,   0,   0,   0,   0,   1,   0],
       [  0,   0,   0,   0,   0,   0,   0,  87]], dtype=int64)

In [66]:
classification_report(y_test,y_pred)

'             precision    recall  f1-score   support\n\n          1       1.00      1.00      1.00       358\n          2       1.00      1.00      1.00       133\n          3       1.00      1.00      1.00       341\n          4       1.00      1.00      1.00       111\n          6       1.00      1.00      1.00       123\n         15       1.00      1.00      1.00         1\n         17       1.00      1.00      1.00         1\n         18       1.00      1.00      1.00        87\n\navg / total       1.00      1.00      1.00      1155\n'

In [55]:
new_house = np.array([7600000,6,1898,6])

In [58]:
new_house1 = mm.fit_transform(new_house.reshape(1,-1))

C:\Users\7314315\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

In [60]:
clf.predict(new_house1)

array([1], dtype=int64)

## new_house=mm.fit_transform(new_house)

# n_neighbors : int, optional (default = 5)

Number of neighbors to use by default for kneighbors queries.

weights : str or callable, optional (default = ‘uniform’)

weight function used in prediction. Possible values:

‘uniform’ : uniform weights. All points in each neighborhood are weighted equally.
‘distance’ : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.
[callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.
algorithm : {‘auto’, ‘ball_tree’, ‘kd_tree’, ‘brute’}, optional

Algorithm used to compute the nearest neighbors:

‘ball_tree’ will use BallTree
‘kd_tree’ will use KDTree
‘brute’ will use a brute-force search.
‘auto’ will attempt to decide the most appropriate algorithm based on the values passed to fit method.
Note: fitting on sparse input will override the setting of this parameter, using brute force.

leaf_size : int, optional (default = 30)

Leaf size passed to BallTree or KDTree. This can affect the speed of the construction and query, as well as the memory required to store the tree. The optimal value depends on the nature of the problem.

p : integer, optional (default = 2)

Power parameter for the Minkowski metric. When p = 1, this is equivalent to using manhattan_distance (l1), and euclidean_distance (l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.

metric : string or callable, default ‘minkowski’

the distance metric to use for the tree. The default metric is minkowski, and with p=2 is equivalent to the standard Euclidean metric. See the documentation of the DistanceMetric class for a list of available metrics.

metric_params : dict, optional (default = None)

Additional keyword arguments for the metric function.

n_jobs : int, optional (default = 1)

The number of parallel jobs to run for neighbors search. If -1, then the number of jobs is set to the number of CPU cores. Doesn’t affect fit method

In [42]:
y_test=list(y_test['carb'])

## Evaluating your model's predictions against the test dataset

In [37]:
y_expect = y_test
y_pred = clf.predict(X_test)

NameError: name 'X_test' is not defined

In [45]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.45454545454545453

In [47]:
len(y_test)

11

In [109]:
for n in range(1,10):
    clf = neighbors.KNeighborsClassifier(n_neighbors=n)
    clf.fit(X_train,y_train)
    print(metrics.accuracy_score(y_test, clf.predict(X_test)))

0.5454545454545454
0.5454545454545454
0.45454545454545453
0.45454545454545453
0.45454545454545453
0.45454545454545453
0.5454545454545454
0.36363636363636365
0.2727272727272727

C:\Users\7314315\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\7314315\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\7314315\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\7314315\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\7314315\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\7314315\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\7314315\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\7314315\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\7314315\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

In [63]:
df.corr()

,price,place,sqft,yearsOld,floor,totalFloor,bhk
price,1.000000,0.017520,0.778364,0.215712,0.263472,0.402256,0.263472
place,0.017520,1.000000,0.105978,-0.573264,0.216312,0.199951,0.216312
sqft,0.778364,0.105978,1.000000,0.229461,0.356053,0.358946,0.356053
yearsOld,0.215712,-0.573264,0.229461,1.000000,-0.116427,-0.142562,-0.116427
floor,0.263472,0.216312,0.356053,-0.116427,1.000000,0.958100,1.000000
totalFloor,0.402256,0.199951,0.358946,-0.142562,0.958100,1.000000,0.958100
bhk,0.263472,0.216312,0.356053,-0.116427,1.000000,0.958100,1.000000

In [18]:
y2pred = clf.predict([[12,133,4]])

In [19]:
y2pred

array([4], dtype=int64)

In [27]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB

clf_nb = GaussianNB()
X_train, X_test, y_train, y_test = train_test_split(X_prime, y, test_size=.33, random_state=17)

clf_nb.fit(X_train, y_train)
y_expect = y_test
y_pred = clf_nb.predict(X_test)

print(metrics.classification_report(y_expect, y_pred))
print(metrics.accuracy_score(y_expect, y_pred))
print(metrics.confusion_matrix(y_expect, y_pred))

             precision    recall  f1-score   support

          0       0.83      1.00      0.91         5
          1       1.00      0.83      0.91         6

avg / total       0.92      0.91      0.91        11

0.9090909090909091
[[5 0]
 [1 5]]